### ISSUE TITLE
How to get the current value of the widget?

### ISSUE THREAD

**Issue by notgiorgi** [MyScript/myscript-text-web#2]
I want to capture the current value (result) of the widget.

I attached the event listener to `myscript-text-web-result` but the [docs say nothing](https://myscript.github.io/myscript-text-web/components/myscript-text-web/#myscript-text-web:event-myscript-text-web-result) about the object it passes as argument in the callback.

I guess `event.detail.result.textSegmentResult.candidates[0].label` is the whole result right?

**Comment by padewitte** [comment]
Yes you are right. `event.detail.result.textSegmentResult.candidates` is an array containing all the candidates from the recognition engine. We will improve deeply the documentation in the upcoming version. We will address your remark.

The other option is to read the value of the firstcandidate attribute.

**Comment by notgiorgi** [comment]
> We will improve deeply the documentation in the upcoming version
That would be great

> The other option is to read the value of the firstcandidate attribute.

just found that, thanks.

**Comment by notgiorgi** [comment]
Also the web demo is not working: https://myscript.github.io/myscript-text-web/components/myscript-text-web/#myscript-text-web:event-myscript-text-web-result
