### ISSUE TITLE
Install language web app

### ISSUE THREAD

**Issue by Eduardomoberti** [MyScript/myscript-text-web#3]
Hi, I am trying to install new package language, but I can´t find how to do that.

**Comment by padewitte** [comment]
Hi,
[This example](https://myscript.github.io/myscript-text-web/components/myscript-text-web/#/elements/myscript-text-web/demos/customize-style-and-change-fonts-[v4]) with the [associate code](https://github.com/MyScript/myscript-text-web/blob/master/examples/non-version-specific/customize_style.html) can help you.

The `language`is the one to set properly. The list of supported language in `V4` with the associated key is available [here](https://github.com/MyScript/MyScriptJS/blob/master/src/configuration/languages.json)

Regards
